# Generated by Django 5.2.15 on 2026-06-26 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='current_amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.goal'),
        ),
    ]
